---
- name: Configure Docker on Deployserver
  hosts: Deployserver
  become: true
  tasks:
    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install Python and Pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image from DockerHub
      command: docker pull atul0074/my-app:1.0

    - name: Run Docker container
      command: docker run -itd -p 8080:8081 atul0074/my-app:1.0
